using HrManager.Application.Common.Dtos.AttendanceRecordReportDtos;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using OfficeOpenXml.Drawing;
using OfficeOpenXml.Drawing.Chart;
using OfficeOpenXml.Style;
using System.Drawing;

namespace HrManager.Application.Common.Services;

public class ReportService(IApplicationDbContext context) : IReportService
{
    private readonly Color PrimaryColor = Color.FromArgb(41, 128, 185);
    private readonly Color SecondaryColor = Color.FromArgb(236, 240, 241);

    public async Task<ExcelWorksheet> CreateReportTemplateAsync(ExcelPackage package, string title, int columnCount)
    {
        var ws = package.Workbook.Worksheets.Add(title);

        var logoPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "logo.png");
        if (File.Exists(logoPath))
        {
            using var fs = new FileStream(logoPath, FileMode.Open, FileAccess.Read);
            var drawing = ws.HeaderFooter.OddHeader.InsertPicture(fs, ePictureType.Png, PictureAlignment.Left);
            drawing.Width = 75;
            drawing.Height = 56;
        }

        ws.HeaderFooter.OddHeader.RightAlignedText = $"Generated: {DateTime.Now:yyyy-MM-dd}";
        ws.HeaderFooter.OddHeader.CenteredText = title;

        ws.Cells[1, 1, 1, columnCount].Merge = true;
        ws.Cells[1, 1, 1, columnCount].Value = title;
        ws.Cells[1, 1, 1, columnCount].Style.Font.Bold = true;
        ws.Cells[1, 1, 1, columnCount].Style.Font.Size = 20;
        ws.Cells[1, 1, 1, columnCount].Style.Font.Color.SetColor(Color.White);
        ws.Cells[1, 1, 1, columnCount].Style.Fill.PatternType = ExcelFillStyle.Solid;
        ws.Cells[1, 1, 1, columnCount].Style.Fill.BackgroundColor.SetColor(PrimaryColor);
        ws.Cells[1, 1, 1, columnCount].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
        ws.Row(1).Height = 30;

        ws.PrinterSettings.Orientation = eOrientation.Landscape;
        ws.PrinterSettings.LeftMargin = 0.5d;
        ws.PrinterSettings.RightMargin = 0.5d;
        ws.PrinterSettings.TopMargin = 0.75d;
        ws.PrinterSettings.BottomMargin = 0.75d;

        ws.HeaderFooter.OddFooter.CenteredText =
            $"Generated by HR Manager | Report Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}";

        return ws;
    }

    public async Task<byte[]> ExportEmployeeListAsync(Guid? departmentId = null, DateOnly? startDate = null, DateOnly? endDate = null)
    {
        var query = context.Employees
             .Include(e => e.Department)
             .Include(e => e.Position)
             .AsNoTracking()
             .AsQueryable();

        if (departmentId.HasValue)
        {
            query = query.Where(e => e.DepartmentId == departmentId.Value);
        }

        if (startDate.HasValue)
        {
            query = query.Where(e => e.HireDate >= startDate.Value);
        }

        if (endDate.HasValue)
        {
            query = query.Where(e => e.HireDate <= endDate.Value);
        }

        var employees = await query.ToListAsync();

        using var package = new ExcelPackage();
        var headers = new[] { "ID", "Full Name", "Email", "Phone", "Department", "Position", "Hire Date" };

        var ws = await CreateReportTemplateAsync(package, "Employee List", headers.Length);

        for (int i = 0; i < headers.Length; i++)
        {
            ws.Cells[3, i + 1].Value = headers[i];
        }

        ApplyHeaderStyle(ws.Cells[3, 1, 3, headers.Length]);

        int row = 4;
        foreach (var e in employees)
        {
            ws.Cells[row, 1].Value = e.Id;
            ws.Cells[row, 2].Value = $"{e.LastName} {e.FirstName} {e.MiddleName}";
            ws.Cells[row, 3].Value = e.Email;
            ws.Cells[row, 4].Value = e.PhoneNumber;
            ws.Cells[row, 5].Value = e.Department?.Name;
            ws.Cells[row, 6].Value = e.Position?.Title;
            ws.Cells[row, 7].Value = e.HireDate.ToString("yyyy-MM-dd");
            row++;
        }

        ApplyAlternateRowColor(ws, 4, row - 1, headers.Length);

        ws.Cells[3, 1, row - 1, headers.Length].Style.Border.BorderAround(ExcelBorderStyle.Thin);
        ws.Cells.AutoFitColumns();

        return await package.GetAsByteArrayAsync();
    }

    public async Task<byte[]> GenerateDepartmentSummaryReportAsync(Guid? departmentId = null)
    {
        var query = context.Departments
           .Include(d => d.Employees)
           .AsNoTracking()
           .AsQueryable();

        if (departmentId.HasValue)
        {
            query = query.Where(d => d.Id == departmentId.Value);
        }

        var departments = await query.ToListAsync();

        var summaries = departments.Select(dept =>
        {
            var employees = dept.Employees.ToList();
            int total = employees.Count;
            int active = employees.Count(e => e.TerminationDate == null);
            int inactive = employees.Count(e => e.TerminationDate != null);

            double avgTenure = employees.Any()
                ? employees.Average(e =>
                {
                    var endDate = e.TerminationDate?.ToDateTime(TimeOnly.MinValue) ?? DateTime.Now;
                    return (endDate - e.HireDate.ToDateTime(TimeOnly.MinValue)).TotalDays / 365;
                })
                : 0;

            return new
            {
                DepartmentName = dept.Name,
                TotalEmployees = total,
                ActiveCount = active,
                InactiveCount = inactive,
                AverageTenure = Math.Round(avgTenure, 2),
            };
        }).ToList();

        using var package = new ExcelPackage();
        var headers = new[] { "Department Name", "Total Employees", "Active", "Inactive", "Avg Tenure (Years)" };

        var ws = await CreateReportTemplateAsync(package, "Department Summary", headers.Length);

        for (int i = 0; i < headers.Length; i++)
        {
            ws.Cells[3, i + 1].Value = headers[i];
        }

        ApplyHeaderStyle(ws.Cells[3, 1, 3, headers.Length]);

        int row = 4;
        foreach (var s in summaries)
        {
            ws.Cells[row, 1].Value = s.DepartmentName;
            ws.Cells[row, 2].Value = s.TotalEmployees;
            ws.Cells[row, 3].Value = s.ActiveCount;
            ws.Cells[row, 4].Value = s.InactiveCount;
            ws.Cells[row, 5].Value = s.AverageTenure;
            row++;
        }

        ApplyAlternateRowColor(ws, 4, row - 1, headers.Length);

        if (summaries.Count > 0)
        {
            var chart = ws.Drawings.AddChart("DeptSummaryChart", eChartType.ColumnClustered);
            chart.Title.Text = "Employees by Department";
            chart.SetPosition(1, 0, 7, 0);
            chart.SetSize(700, 400);

            chart.Series.Add(ws.Cells[$"B4:B{row - 1}"], ws.Cells[$"A4:A{row - 1}"]).Header = "Total Employees";
            chart.Series.Add(ws.Cells[$"C4:C{row - 1}"], ws.Cells[$"A4:A{row - 1}"]).Header = "Active";
            chart.Series.Add(ws.Cells[$"D4:D{row - 1}"], ws.Cells[$"A4:A{row - 1}"]).Header = "Inactive";

            var valueAxis = chart.YAxis;
            valueAxis.MajorUnit = 1;
            valueAxis.MinValue = 0;
            valueAxis.MaxValue = Math.Ceiling(summaries.Max(s => (double)s.TotalEmployees));
            valueAxis.Format = "0";
        }
        else
        {
            ws.Cells["A4"].Value = "No data available to display.";
        }

        ws.Cells.AutoFitColumns();
        return await package.GetAsByteArrayAsync();
    }

    private void ApplyHeaderStyle(ExcelRange range)
    {
        range.Style.Font.Bold = true;
        range.Style.Font.Color.SetColor(Color.White);
        range.Style.Fill.PatternType = ExcelFillStyle.Solid;
        range.Style.Fill.BackgroundColor.SetColor(PrimaryColor);
        range.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
        range.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
    }

    private void ApplyAlternateRowColor(ExcelWorksheet ws, int rowStart, int rowEnd, int colEnd)
    {
        for (int row = rowStart; row <= rowEnd; row++)
        {
            if (row % 2 == 0)
            {
                using var range = ws.Cells[row, 1, row, colEnd];
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(SecondaryColor);
            }
        }
    }

    public async Task<byte[]> ExportAttendanceSummaryAsync(
        List<AttendanceSummaryReportDto> data,
        DateOnly? startDate,
        DateOnly endDate)
    {
        using var package = new ExcelPackage();

        var detailedHeaders = new[]
        {
        "Record #", "Employee", "Department", "Days Worked", "Late Arrivals",
        "Early Departures", "Total Hours", "Overtime (Hours)",
        };

        var ws = await CreateReportTemplateAsync(package, "Attendance Summary Report", detailedHeaders.Length);

        int detailedHeaderRow = 3;
        int detailedStartRow = detailedHeaderRow + 1;

        for (int i = 0; i < detailedHeaders.Length; i++)
        {
            ws.Cells[detailedHeaderRow, i + 1].Value = detailedHeaders[i];
        }

        ApplyHeaderStyle(ws.Cells[detailedHeaderRow, 1, detailedHeaderRow, detailedHeaders.Length]);

        int row = detailedStartRow;
        int recordNumber = 1;

        foreach (var item in data)
        {
            ws.Cells.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
            ws.Cells[row, 1].Value = recordNumber++;
            ws.Cells[row, 2].Value = item.EmployeeFullName;
            ws.Cells[row, 3].Value = item.DepartmentName;
            ws.Cells[row, 4].Value = item.TotalDaysWorked;
            ws.Cells[row, 5].Value = item.TotalLateArrivals;
            ws.Cells[row, 6].Value = item.TotalEarlyDepartures;
            ws.Cells[row, 7].Value = FormatHoursMinutes(item.TotalWorkMinutes);
            ws.Cells[row, 8].Value = FormatHoursMinutes(item.TotalOvertimeMinutes);

            row++;
        }

        var totals = new string[]
        {
            "Total: ",
            "Employees: " + data.Select(d => d.EmployeeFullName).Distinct().Count(),
            "Departments: " + data.Select(d => d.DepartmentName).Distinct().Count(),
            "Days Worked: " + data.Sum(x => x.TotalDaysWorked),
            "Late Arrivals: " + data.Sum(x => x.TotalLateArrivals),
            "Early Departures: " + data.Sum(x => x.TotalEarlyDepartures),
            "Work Hours: " + FormatHoursMinutes(data.Sum(x => x.TotalWorkMinutes)),
            "Overtime Hours: " + FormatHoursMinutes(data.Sum(x => x.TotalOvertimeMinutes)),
        };

        for (int i = 0; i < totals.Length; i++)
        {
            ws.Cells[row, i + 1].Value = totals[i];
        }

        ws.Cells[row, 1, row, 8].Style.Font.Bold = true;
        ws.Cells[row, 1, row, 8].Style.Fill.PatternType = ExcelFillStyle.Solid;
        ws.Cells[row, 1, row, 8].Style.Fill.BackgroundColor.SetColor(Color.LightGray);

        ApplyAlternateRowColor(ws, detailedStartRow, row - 1, detailedHeaders.Length);
        ws.Cells.AutoFitColumns();
        return await package.GetAsByteArrayAsync();
    }

    public async Task<byte[]> ExportLateArrivalReportAsync(List<LateArrivalReportDto> data)
    {
        using var package = new ExcelPackage();

        var detailedHeaders = new[]
        {
            "Record #", "Employee", "Department", "Date", "Check-In", "Late Hours", "Frequency", "Total Late Hours",
        };

        var ws = await CreateReportTemplateAsync(package, "Late Arrival Report", detailedHeaders.Length);

        int detailedHeaderRow = 3;
        int detailedStartRow = detailedHeaderRow + 1;
        for (int i = 0; i < detailedHeaders.Length; i++)
        {
            ws.Cells[detailedHeaderRow, i + 1].Value = detailedHeaders[i];
        }

        ApplyHeaderStyle(ws.Cells[detailedHeaderRow, 1, detailedHeaderRow, detailedHeaders.Length]);

        int row = detailedStartRow;
        int recordNumber = 1;
        Guid? currentEmployeeId = null;
        int frequency = 0;
        int cumulativeMinutes = 0;

        foreach (var record in data)
        {
            if (currentEmployeeId != record.EmployeeId)
            {
                currentEmployeeId = record.EmployeeId;
                frequency = 1;
                cumulativeMinutes = 0;
            }
            else
            {
                frequency++;
            }

            cumulativeMinutes += record.LateMinutes;

            ws.Cells[row, 1].Value = recordNumber++;
            ws.Cells[row, 1].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
            ws.Cells[row, 2].Value = record.EmployeeFullName;
            ws.Cells[row, 3].Value = record.DepartmentName;
            ws.Cells[row, 4].Value = record.Date.ToString("yyyy-MM-dd");
            ws.Cells[row, 5].Value = record.CheckIn.ToString("HH:mm");
            ws.Cells[row, 6].Value = FormatHoursMinutes(record.LateMinutes);
            ws.Cells[row, 7].Value = frequency;
            ws.Cells[row, 8].Value = FormatHoursMinutes(cumulativeMinutes);

            ws.Cells[row, 7].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;

            row++;
        }

        ApplyAlternateRowColor(ws, detailedStartRow, row - 1, detailedHeaders.Length);
        ws.Cells.AutoFitColumns();
        return await package.GetAsByteArrayAsync();
    }

    public async Task<byte[]> ExportOvertimeReportAsync(List<OvertimeReportDto> data)
    {
        using var package = new ExcelPackage();
        var headers = new[]
        {
        "Record #", "Employee", "Department", "Date", "Overtime (Minutes)", "Overtime Cost",
        };
        var ws = await CreateReportTemplateAsync(package, "Overtime Report", headers.Length);

        int headerRow = 3;
        int startRow = headerRow + 1;
        for (int i = 0; i < headers.Length; i++)
        {
            ws.Cells[headerRow, i + 1].Value = headers[i];
        }

        ApplyHeaderStyle(ws.Cells[headerRow, 1, headerRow, headers.Length]);

        int row = startRow;
        int recordNumber = 1;

        foreach (var item in data)
        {
            ws.Cells.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
            ws.Cells[row, 1].Value = recordNumber++;
            ws.Cells[row, 2].Value = item.EmployeeFullName;
            ws.Cells[row, 3].Value = item.DepartmentName;
            ws.Cells[row, 4].Value = item.Date.ToString("yyyy-MM-dd");
            ws.Cells[row, 5].Value = FormatHoursMinutes(item.OvertimeMinutes);
            ws.Cells[row, 6].Value = "$" + item.OvertimeCost.ToString("0.00");

            row++;
        }

        var totals = new string[]
        {
            "Total:",
            "Employees: " + data.Select(d => d.EmployeeFullName).Distinct().Count(),
            "Departments: " + data.Select(d => d.DepartmentName).Distinct().Count(),
            "Days: " + data.Select(d => d.Date).Distinct().Count(),
            "Overtime: " + FormatHoursMinutes(data.Sum(x => x.OvertimeMinutes)),
            "Cost: $" + data.Sum(x => x.OvertimeCost).ToString("0.00"),
        };

        for (int i = 0; i < totals.Length; i++)
        {
            ws.Cells[row, i + 1].Value = totals[i];
        }

        ws.Cells[row, 1, row, headers.Length].Style.Font.Bold = true;
        ws.Cells[row, 1, row, headers.Length].Style.Fill.PatternType = ExcelFillStyle.Solid;
        ws.Cells[row, 1, row, headers.Length].Style.Fill.BackgroundColor.SetColor(Color.LightGray);

        ApplyAlternateRowColor(ws, startRow, row - 1, headers.Length);
        ws.Cells.AutoFitColumns();
        return await package.GetAsByteArrayAsync();
    }

    public async Task<byte[]> ExportAttendancePercentageReportAsync(List<AttendancePercentageReportDto> data)
    {
        using var package = new ExcelPackage();

        var detailedHeaders = new[]
        {
        "Record #", "Employee", "Department", "Period Start", "Period End", "Attendance %",
        };

        var ws = await CreateReportTemplateAsync(package, "Attendance Percentage Report", detailedHeaders.Length);

        int detailedHeaderRow = 3;
        int detailedStartRow = detailedHeaderRow + 1;

        for (int i = 0; i < detailedHeaders.Length; i++)
        {
            ws.Cells[detailedHeaderRow, i + 1].Value = detailedHeaders[i];
        }

        ApplyHeaderStyle(ws.Cells[detailedHeaderRow, 1, detailedHeaderRow, detailedHeaders.Length]);

        int row = detailedStartRow;
        int recordNumber = 1;

        foreach (IGrouping<Guid, AttendancePercentageReportDto> group in data.GroupBy(x => x.EmployeeId))
        {
            var first = group.First();
            int attendedDays = group.Count();

            int totalDays =
                (first.PeriodEndDate.DayNumber - first.PeriodStartDate.DayNumber) + 1;

            double attendancePercentage = totalDays > 0
                ? Math.Round((double)attendedDays / totalDays * 100, 2)
                : 0;

            ws.Cells[row, 1].Value = recordNumber++;
            ws.Cells[row, 2].Value = first.EmployeeFullName;
            ws.Cells[row, 3].Value = first.DepartmentName;
            ws.Cells[row, 4].Value = first.PeriodStartDate.ToString("yyyy-MM-dd");
            ws.Cells[row, 5].Value = first.PeriodEndDate.ToString("yyyy-MM-dd");
            ws.Cells[row, 6].Value = attendancePercentage / 100.0;
            ws.Cells[row, 6].Style.Numberformat.Format = "0.00%";

            ws.Cells[row, 1, row, 6].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;

            row++;
        }

        ApplyAlternateRowColor(ws, detailedStartRow, row - 1, detailedHeaders.Length);
        ws.Cells.AutoFitColumns();

        return await package.GetAsByteArrayAsync();
    }

    private static string FormatHoursMinutes(int totalMinutes)
    {
        if (totalMinutes <= 0)
        {
            return "0h 0m";
        }

        var hours = totalMinutes / 60;
        var minutes = totalMinutes % 60;
        return $"{hours}h {minutes}m";
    }
}
